### ISSUE TITLE
URLError

### ISSUE THREAD

**Issue by eepp** [Paaskehare/pastebin-sublime-plugin#5]
Hello,

Recently, I'm getting this:

```
Traceback (most recent call last):
  File "/home/user/goodies/sublime_text_3/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/home/user/.config/sublime-text-3/Packages/pastebin-sublime-plugin/pastebin.py", line 115, in run
    reply = urllib2.urlopen(request).read().decode(FilePart.CONTENT_TRANSFER_ENCODING)
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 469, in open
  File "./urllib/request.py", line 492, in _open
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1310, in unknown_open
urllib.error.URLError: <urlopen error unknown url type: https>
```

I'm using ST3 build 3083, latest pastebin-sublime-plugin.

**Comment by Paaskehare** [comment]
Hello eepp. Sorry for the long wait. It seems that the python version that's bundled with recent versions of st3 is not compiled with ssl support. I altered the plugin to use http instead so it should work fine. It will still return a https url for pasting atleast.

**Comment by eepp** [comment]
Ok great! I switched to [pastery](https://packagecontrol.io/packages/Pastery) in the meantime, but I'll check this out when I have time.
